[phases.setup]
aptPkgs = [
    "python3",
    "python3-pip",
    "pkg-config",
    "libcairo2-dev",
    "libpango1.0-dev",
    "libjpeg-dev",
    "libgif-dev",
    "librsvg2-dev",
    "build-essential"
]

[phases.install]
cmds = ["npm ci"]

[env]
PYTHON = "python3"
PATH = "/usr/local/bin:${PATH}"