[phases.setup]
nixPkgs = [
    "cairo",
    "pkg-config",
    "python3",
    "nodejs",
    "pixman",
    "pango"
]

[phases.build]
cmds = [
    "sudo apt-get update",
    "sudo apt-get install -y libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev libpixman-1-dev pkg-config",
    "export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/share/pkgconfig:$PKG_CONFIG_PATH"
]

[phases.install]
cmds = ["npm install"]

[start]
cmd = "node src/server.js"

[variables]
PKG_CONFIG_PATH = "/usr/lib/x86_64-linux-gnu/pkgconfig:/usr/share/pkgconfig"