[phases.setup]
nixPkgs = ["python3", "python3-pip"]
aptPkgs = [
    "pkg-config",
    "libcairo2-dev",
    "libpango1.0-dev",
    "libjpeg-dev",
    "libgif-dev",
    "librsvg2-dev",
    "build-essential"
]

[phases.install]
cmds = ["npm ci"]

[env]
PYTHON = "python3"
NIXPACKS_PYTHON = "python3"
NIXPACKS_PYTHON_VERSION = "3.11"