[phases.setup]
aptPkgs = [
    "python3",
    "python3-pip",
    "pkg-config",
    "libcairo2-dev",
    "libpango1.0-dev",
    "libjpeg-dev",
    "libgif-dev",
    "librsvg2-dev",
    "build-essential",
    "libcairo2",
    "libxi6",
    "libglib2.0-0",
    "libpangocairo-1.0-0",
    "libpango1.0-0",
    "libpango-1.0-0"
]

[phases.install]
cmds = ["npm ci"]

[env]
PYTHON = "python3"
PATH = "/usr/local/bin:${PATH}"
LD_LIBRARY_PATH = "/usr/local/lib:/usr/lib:/lib"