[phases.setup]
apt_packages = [
    "python3",
    "pkg-config",
    "libcairo2-dev",
    "libpango1.0-dev",
    "libjpeg-dev",
    "libgif-dev",
    "librsvg2-dev",
    "build-essential",
    "python3-pip"
]

[phases.install]
cmds = ["npm ci"]

[env]
PYTHON = "python3"
PATH = "/usr/local/bin:${PATH}"