[phases.setup]
nixpkgs = ["nodejs-20_x", "pkg-config", "cairo", "pango", "libpng", "jpeg", "giflib", "librsvg"]

[phases.install]
command = """
apk add --no-cache build-base g++ cairo-dev pango-dev giflib-dev libjpeg-turbo-dev
npm ci
"""
