[phases.setup]
nixPkgs = [
    "cairo",
    "pkg-config",
    "python3",
    "nodejs",
    "pixman"  # Added pixman package
]

[phases.build]
cmds = [
    "sudo apt-get update",
    "sudo apt-get install -y libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev libpixman-1-dev"  # Added libpixman-1-dev
]

[phases.install]
cmds = ["npm install"]

[start]
cmd = "node src/server.js"