[phases.setup]
nixPkgs = [
    "cairo",
    "pkg-config",
    "python3",
    "nodejs"
]

[phases.build]
cmds = [
    "sudo apt-get update",
    "sudo apt-get install -y libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev"
]

[phases.install]
cmds = ["npm ci"]

[start]
cmd = "node server.js"