[phases.setup]
nixPkgs = [
    "nodejs-18_x",
    "python3",
    "cairo",
    "pkg-config",
    "libpng",
    "pango",
    "libjpeg",
    "giflib",
    "librsvg"
]

[phases.build]
cmds = [
    "export PYTHON=/usr/bin/python3",
    "apt-get update",
    "apt-get install -y build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev python3"
]

[phases.install]
cmds = ["npm ci"]

[start]
cmd = "node src/server.js"