[phases.setup]
nixPkgs = [
    "python3",
    "pkg-config",
    "cairo",
    "pango",
    "libjpeg",
    "giflib",
    "librsvg",
    "nodejs"
]

[phases.install]
cmds = [
    "python3 -m ensurepip",
    "npm config set python python3",
    "npm ci"
]

[start]
cmd = "node src/server.js"

[variables]
PYTHON = "python3"